-- Keymaps
vim.keymap.set("n", "<Space>gg", function()
	vim.cmd("Git")
end)
vim.keymap.set("n", "<Space>gp", function()
	vim.cmd("Git push")
end)
vim.keymap.set("n", "<Space>gu", function()
	vim.cmd("Git pull")
end)
vim.keymap.set("n", "<Space>gc", function()
	vim.cmd("Git pull")
end)
