#!/bin/sh

down() {
pamixer -d 5
volume=$(pamixer --get-volume)
[$volume -gt 0 ] && volume=`expr $volume`  
notify-send -a "VOLUME" "Decreasing to $volume%" -h int:value:"$volume" -r 1 -u normal
}

up() {
pamixer -i 5
volume=$(pamixer --get-volume)
[ $volume -lt 1000 ] && volume=`expr $volume`  
dunstify -a "VOLUME" "Increasing to $volume%" -h int:value:"$volume" -r 1 -u normal
}

mute() {
muted="$(pamixer --get-mute)"
if $muted; then
  pamixer -u
  dunstify -a "VOLUME" "UNMUTED" -r 2593 -u normal
else 
  pamixer -m
  dunstify -a "VOLUME" "MUTED" -r 2593 -u normal
fi
}

case "$1" in
  up) up;;
  down) down;;
  mute) mute;;
esac
