#!/bin/sh

down() {
brightnessctl set 5%-
brightness=$(light -g)
dunstify -a "BRIGHTNESS" "Decreasing to $brightness%" -h int:value:"$brightness" -r 1 -u normal
}

up() {
brightnessctl set 5%+
brightness=$(light -g)
dunstify -a "BRIGHTNESS" "Increasing to $brightness%" -h int:value:"$brightness" -r 1 -u normal
}

case "$1" in
  up) up;;
  down) down;;
esac
